name: "CI"
on:
  push:
    branches:
      - "master"
      - "for-master"
      - "patchset/**"
  pull_request:
    branches:
      - "master"
jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent:
          - aider
          - cecli
          - claude
          - codex
          - copilot
          - gemini
          - goose
          - grok
          - kimi
          - opencode
          - vibe
      fail-fast: false
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v6

      - name: "Prepare"
        run: sudo chmod 666 /dev/tty60

      - name: "Configure"
        run: |
          ./devkit.sh init

          git config set devkit.agent ${{ matrix.agent }}
          git config set --append devkit.packages git
          git config set --append devkit.packages jq

      - name: "Check"
        run: |
          ./devkit.sh exec stat /usr/local/bin/${{ matrix.agent }}    </dev/tty60
          ./devkit.sh exec test -x /usr/local/bin/${{ matrix.agent }} </dev/tty60
          ./devkit.sh shell -c "command -v jq"                        </dev/tty60

      - name: "Version"
        run: |
          [ '${{ matrix.agent }}' = 'gemini' ] || ./devkit.sh run --version </dev/tty60
